# Generated by Django 5.2.9 on 2025-12-13 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=10, verbose_name='address type')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='label')),
                ('full_address', models.TextField(verbose_name='full address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='apartment/unit')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='building')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='floor')),
                ('notes', models.TextField(blank=True, verbose_name='delivery notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user address',
                'verbose_name_plural': 'user addresses',
                'ordering': ['-is_default', 'created_at'],
                'unique_together': {('user', 'label')},
            },
        ),
    ]
