# Generated by Django 5.2.9 on 2026-01-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12, verbose_name='longitude'),
        ),
    ]
