# Generated by Django 5.2.9 on 2026-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_useraddress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=11, max_digits=12, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=11, max_digits=12, verbose_name='longitude'),
        ),
    ]
