# Generated by Django 5.2.9 on 2025-12-13 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('online', 'Online Payment')], default='cash', max_length=20, verbose_name='payment method')),
                ('payment_status', models.BooleanField(default=False, verbose_name='payment status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total amount')),
                ('delivery_address', models.TextField(verbose_name='delivery address')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='delivery latitude')),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='delivery longitude')),
                ('special_instructions', models.TextField(blank=True, verbose_name='special instructions')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='prepared at')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='dispatched at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price at time of order')),
                ('special_request', models.TextField(blank=True, verbose_name='special request')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
    ]
