# Generated by Django 5.2.9 on 2026-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=12, null=True, verbose_name='delivery latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=12, null=True, verbose_name='delivery longitude'),
        ),
    ]
